[logging]
level = "DEBUG"

[api]
host = "0.0.0.0"
port = 8800
frontend_url = "http://localhost:5173"
app_name = "Codeborn"
auto_reload = true

[auth]
cookie_domain = 'localhost'
secure_cookie = false

[auth.jwt]
algorithm = 'HS256'
ttl = 86400 # 24 * 60 * 60

[agents]
runtime_class_name = "codeborn.engine.agents.container.DockerAgent"
base_dir = "~/user_data"
container_image = "localhost/codeborn-client:latest"
version_file = "codeborn.ini"

[lifecycle]

[lifecycle.heartbeat]
interval = 5.0
timeout = 25.0

[lifecycle.restart]
interval = 10.0

[lifecycle.state_update]
interval = 15.0

[database]
init_schema = true
pool_min_size = 2
pool_max_size = 10
timeout = 30.0
command_timeout = 30.0
models = ["codeborn.model", "aerich.models"]

[github]
redirect_url="http://localhost:8800/auth/github/callback"
access_token_url='https://github.com/login/oauth/access_token'
authorize_url='https://github.com/login/oauth/authorize'
api_base_url='https://api.github.com/'
scope=['read:user', 'repo']

[generators]

[generators.map]
width = 100
height = 100

[terrain]

[terrain.plains]
movement_cost = 0.25

[terrain.forest]
movement_cost = 0.5

[units]

[units.light_infantry]
stamina_recovery = 0.0020

[units.heavy_infantry]
stamina_recovery = 0.0015

[units.spearmen]
stamina_recovery = 0.0018

[units.light_cavalry]
stamina_recovery = 0.0022

[units.heavy_cavalry]
stamina_recovery = 0.0016

[units.archer]
stamina_recovery = 0.0023

[units.crossbowman]
stamina_recovery = 0.0021