# syntax=docker/dockerfile:1
FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY codeborn /app/codeborn
COPY codeborn/client/pyproject.toml /app/pyproject.toml

RUN pip install --no-cache-dir .[user]