- hosts: all
  become: yes
  vars:
    service_name: codeborn-api
    user: codeborn

  tasks:
    - name: Create systemd service for FastAPI app
      copy:
        dest: "/etc/systemd/system/{{ service_name }}.service"
        content: |
          [Unit]
          Description=Codeborn FastAPI service
          After=network.target postgresql.service

          [Service]
          User={{ user }}
          WorkingDirectory={{ app_root }}
          EnvironmentFile={{ app_root }}/.env
          EnvironmentFile=-{{ app_root }}/.production.env
          Environment=PYTHONPATH={{ app_root }}
          ExecStart={{ venv_path }}/bin/python -m codeborn.api
          Restart=always
          RestartSec=3

          [Install]
          WantedBy=multi-user.target
      notify: Reload systemd

    - name: Enable and start service
      systemd:
        name: "{{ service_name }}"
        enabled: true
        state: started

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload
