- hosts: all
  become: yes

  vars_files:
    - ../.production.secrets.yml

  tasks:
    - name: Ensure /etc/secret exists
      file:
        path: /etc/secret
        state: directory
        owner: root
        group: "{{ group }}"
        mode: "0750"

    - name: Write app vault password file
      copy:
        content: "{{ ansible.vault_pass }}"
        dest: "{{ vault_pass_file }}"
        owner: root
        group: "{{ group }}"
        mode: "0640"

    - import_tasks: tasks/ensure_env.yml

    - name: Install uv and uvx globally
      ansible.builtin.shell: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
      args:
        creates: "{{ uv_local_bin }}"

    - name: Symlink uv to global bin for global access
      ansible.builtin.file:
        src: "{{ uv_local_bin }}"
        dest: "{{ uv_global_bin }}"
        state: link
        force: yes

    - name: Ensure uv binary is executable
      ansible.builtin.file:
        path: "{{ uv_global_bin }}"
        mode: '0755'

    - name: Create virtual environment using uv
      ansible.builtin.command: "{{ uv_global_bin }} venv --python {{ python_bin }}"
      args:
        chdir: "{{ app_root }}"
        creates: "{{ venv_path }}/bin/python"

    - import_tasks: tasks/sync_python_deps.yml
    
    - name: Ensure agents data directory exists
      file:
        path: "{{ agents.base_dir }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ group }}"
        mode: "0750"
