- hosts: all
  become: yes

  vars_files:
    - ../.production.secrets.yml

  tasks:
    - import_tasks: tasks/secrets/vault_password.yml
    - import_tasks: tasks/ensure_dot_env.yml
    - import_tasks: tasks/python_deps/uv_bin.yml
    - import_tasks: tasks/python_deps/venv.yml
    - import_tasks: tasks/python_deps/install.yml
    
    - name: Ensure agents data directory exists
      file:
        path: "{{ agents.base_dir }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ group }}"
        mode: "0750"
