- hosts: all
  become: yes
  vars_files:
    - ../.production.secrets.yml

  tasks:
    - name: Ensure destination directory exists
      file:
        path: "{{ app_root }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ group }}"
        mode: "0755"

    - name: Ensure .ssh directory exists for deploy key
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ group }}"
        mode: "0700"

    - name: Write deploy private key from vault
      copy:
        content: "{{ deploy_key.private }}"
        dest: "{{ deploy_key_path }}"
        owner: "{{ username }}"
        group: "{{ group }}"
        mode: "0600"

    - name: Write deploy public key from vault
      copy:
        content: "{{ deploy_key.public }}"
        dest: "{{ deploy_key_path }}.pub"
        owner: "{{ username }}"
        group: "{{ group }}"
        mode: "0644"

    - name: Configure SSH for GitHub
      become_user: "{{ username }}"
      copy:
        dest: "/home/{{ username }}/.ssh/config"
        content: |
          Host github.com
            IdentityFile {{ deploy_key_path }}
            IdentitiesOnly yes
        owner: "{{ username }}"
        group: "{{ group }}"
        mode: "0600"

    - import_tasks: tasks/pull_repo.yml
