- hosts: all
  become: yes
  vars:
    app_root: /srv/codeborn
    frontend_dir: "{{ app_root }}/codeborn/client"
    domain: codeborn.app
    email: jakub@tesarek.me
  tasks:
    - name: Install node and npm
      apt:
        name:
          - nodejs
          - npm
        state: present
        update_cache: yes

    - name: Install dependencies and build frontend
      become_user: codeborn
      shell: |
        npm ci
        npm run build
      args:
        chdir: "{{ frontend_dir }}"
        creates: "{{ frontend_dir }}/dist/index.html"

    - name: Create Nginx config for frontend
      copy:
        dest: "/etc/nginx/sites-available/{{ domain }}"
        content: |
          server {
              listen 80;
              server_name {{ domain }} www.{{ domain }};

              root {{ frontend_dir }}/dist;
              index index.html;

              location / {
                  try_files $uri /index.html;
              }

              # Required for Let's Encrypt HTTP-01 validation
              location ~ /.well-known/acme-challenge/ {
                  root /var/www/html;
              }
          }
      notify: Reload Nginx

    - name: Enable site and disable default
      file:
        src: "/etc/nginx/sites-available/{{ domain }}"
        dest: "/etc/nginx/sites-enabled/{{ domain }}"
        state: link
      notify: Reload Nginx

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Reload Nginx

    - name: Obtain SSL certificate for frontend
      command: >
        certbot certonly --webroot
        -w /var/www/html
        --non-interactive --agree-tos
        -m {{ email }}
        -d {{ domain }} -d www.{{ domain }}
      args:
        creates: /etc/letsencrypt/live/{{ domain }}/fullchain.pem

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded