- hosts: all
  become: yes

  tasks:
    - name: Install Nginx and Certbot
      apt:
        name:
          - nginx
          - python3-certbot-nginx
        state: present
        update_cache: yes

    - name: Create systemd service for FastAPI app
      copy:
        dest: "/etc/systemd/system/{{ api_service }}.service"
        content: |
          [Unit]
          Description=Codeborn FastAPI service
          After=network.target postgresql.service

          [Service]
          User={{ username }}
          WorkingDirectory={{ app_root }}
          EnvironmentFile={{ env_file }}
          EnvironmentFile=-{{ prod_env_file }}
          Environment=PYTHONPATH={{ app_root }}
          ExecStart={{ venv_path }}/bin/python -m codeborn.api
          Restart=always
          RestartSec=3

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd
        - Restart API

    - name: Enable and start FastAPI service
      systemd:
        name: "{{ api_service }}"
        enabled: true
        state: started

    - import_tasks: tasks/cert/issue.yml
      vars:
        domain: "{{ domain_api }}"
    
    - import_tasks: tasks/cert/cron_renew.yml

    - name: Install API Nginx config
      template:
        src: templates/nginx_site.j2
        dest: "/etc/nginx/sites-available/{{ domain_api }}"
      vars:
        domain: "{{ domain_api }}"
        proxy_pass: "http://127.0.0.1:8000"
      notify: Reload Nginx

    - import_tasks: tasks/nginx/enable_site.yml
      vars:
        domain: "{{ domain_frontend }}"

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Restart API
      import_tasks: tasks/restart_api.yml

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
