- hosts: all
  become: yes

  tasks:
    - import_tasks: tasks/build_frontend.yml
    - import_tasks: tasks/cert/issue.yml
      vars:
        domain: "{{ domain_frontend }}"
    
    - import_tasks: tasks/cert/cron_renew.yml

    - name: Install frontend Nginx config
      template:
        src: templates/nginx_site.j2
        dest: "/etc/nginx/sites-available/{{ domain_frontend }}"
      vars:
        web_root: "{{ frontend_dist }}"
        domain: "{{ domain_frontend }}"
        extra_domains: "www.{{ domain_frontend }}"
      notify: Reload Nginx

    - import_tasks: tasks/nginx/enable_site.yml
      vars:
        domain: "{{ domain_frontend }}"

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
