- hosts: all
  become: yes

  tasks:
    - import_tasks: tasks/build_frontend.yml
    - import_tasks: tasks/cert/issue.yml
      vars:
        domain: "{{ frontend.domain }}"
    
    - import_tasks: tasks/cert/cron_renew.yml

    - name: Install frontend Nginx config
      template:
        src: templates/nginx_site.j2
        dest: "/etc/nginx/sites-available/{{ frontend.domain }}"
      vars:
        web_root: "{{ frontend_dist }}"
        domain: "{{ frontend.domain }}"
        extra_domains: "www.{{ frontend.domain }}"
      notify: Reload Nginx

    - import_tasks: tasks/nginx/enable_site.yml
      vars:
        domain: "{{ frontend.domain }}"

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
