- name: Ensure secret dir exists
  file:
    path: "{{ vault_pass_file | dirname }}"
    state: directory
    owner: root
    group: "{{ group }}"
    mode: "0750"

- name: Write vault password file
  copy:
    content: "{{ ansible.vault_pass }}"
    dest: "{{ vault_pass_file }}"
    owner: root
    group: "{{ group }}"
    mode: "0640"